### ISSUE TITLE
Poly codec locks up Rest service

### ISSUE THREAD

**Issue by Rodney-Driscoll** [sifuas/PolyVideoOSRestAPI#2]
I have been testing this project on a Poly Studio X50 and the codec locks up after a day of using the module. When locked up a connected TC8 (Poly touch panel) won't be able to connect either and logging into the web page on the codec returns a 502 bad gateway error; meanwhile the codec will still accept SSH connections and commands.
I suspect it is not a fault of the module, rather that the codec does not handle a permanent connection, eventually drops the connection and won't accept a new connection until rebooted.
This is not so much a bug report as a notification that there is an issue with Poly codecs using this module.

**Comment by sifuas** [comment]
I had noticed that as well during my testing. I wasn't sure of the best way to handle it, during my testing it seemed to happen more randomly. Sometimes it would happen after 8 hours, sometimes 24. I decided to leave the module as is and disconnect the device mode controls using the room logic when the device mode was no longer needed. I have some logic on the module to indicate when there is an error and output some logic from it, but that was as far as I took it. I have submitted an issue report to Poly, but I never received a response.

**Comment by sijobnglr** [comment]
Hi sifuas, thank you for sharing the module, i had tested the same with G7500 and i am able to start and stop device mode by debugger.

**Comment by sifuas** [comment]
Currently since there is not way to reset the VideoOS device when this occurs except to power cycle, I am going to leave the code as-is. Users will need to manage the connection from the module to the VideoOS device and connect / disconnect as needed.
